/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.calculadora;
import java.awt.Color;
import java.awt.Frame;
/**
 *
 * @author esteb
 */
public class App extends javax.swing.JFrame {
    int xMouse, yMouse;
    int res = 0;
    int temp, op = 0;
    /**
     * Creates new form App
     */
    public App() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        Barra = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        Icono = new javax.swing.JLabel();
        MinPn = new javax.swing.JPanel();
        MinLb = new javax.swing.JLabel();
        ClosePn = new javax.swing.JPanel();
        CloseLb = new javax.swing.JLabel();
        BtDiv = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Bt9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Bt8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Bt7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BtMult = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        BtClear = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        BtResult = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        BtSum = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        BtRes = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        Bt3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        Bt0 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        Bt2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Bt1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        Bt4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Bt5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        Bt6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        EntryLb = new javax.swing.JLabel();
        Separador = new javax.swing.JSeparator();
        Comando = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Fondo.setBackground(new java.awt.Color(31, 32, 36));
        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Barra.setBackground(new java.awt.Color(31, 32, 36));
        Barra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BarraMouseDragged(evt);
            }
        });
        Barra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BarraMousePressed(evt);
            }
        });
        Barra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("Calculadora");
        Barra.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 150, 50));

        Icono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/calculadora/resources/icon.png"))); // NOI18N
        Barra.add(Icono, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 50, 50));

        MinPn.setBackground(new java.awt.Color(31, 32, 36));
        MinPn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MinPn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MinPnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MinPnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MinPnMousePressed(evt);
            }
        });
        MinPn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MinLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MinLb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/calculadora/resources/down.png"))); // NOI18N
        MinPn.add(MinLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        Barra.add(MinPn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 50, 50));

        ClosePn.setBackground(new java.awt.Color(31, 32, 36));
        ClosePn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ClosePn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ClosePnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ClosePnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ClosePnMousePressed(evt);
            }
        });
        ClosePn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CloseLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CloseLb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/calculadora/resources/close.png"))); // NOI18N
        ClosePn.add(CloseLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        Barra.add(ClosePn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 50, 50));

        Fondo.add(Barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 50));

        BtDiv.setBackground(new java.awt.Color(49, 50, 54));
        BtDiv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtDiv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtDivMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtDivMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BtDivMousePressed(evt);
            }
        });
        BtDiv.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("/");
        BtDiv.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 70, 40));

        Fondo.add(BtDiv, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 90, 80));

        Bt9.setBackground(new java.awt.Color(58, 59, 63));
        Bt9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bt9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Bt9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Bt9MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Bt9MousePressed(evt);
            }
        });
        Bt9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("9");
        Bt9.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 60));

        Fondo.add(Bt9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 90, 80));

        Bt8.setBackground(new java.awt.Color(58, 59, 63));
        Bt8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bt8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Bt8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Bt8MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Bt8MousePressed(evt);
            }
        });
        Bt8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("8");
        Bt8.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 60));

        Fondo.add(Bt8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 90, 80));

        Bt7.setBackground(new java.awt.Color(58, 59, 63));
        Bt7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bt7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Bt7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Bt7MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Bt7MousePressed(evt);
            }
        });
        Bt7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("7");
        Bt7.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 60));

        Fondo.add(Bt7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 90, 80));

        BtMult.setBackground(new java.awt.Color(49, 50, 54));
        BtMult.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtMult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtMultMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtMultMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BtMultMousePressed(evt);
            }
        });
        BtMult.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("x");
        BtMult.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 50));

        Fondo.add(BtMult, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 90, 80));

        BtClear.setBackground(new java.awt.Color(49, 50, 54));
        BtClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtClearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtClearMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BtClearMousePressed(evt);
            }
        });
        BtClear.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("C");
        BtClear.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 50));

        Fondo.add(BtClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 90, 80));

        BtResult.setBackground(new java.awt.Color(49, 50, 54));
        BtResult.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtResult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtResultMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtResultMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BtResultMousePressed(evt);
            }
        });
        BtResult.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("=");
        BtResult.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 50));

        Fondo.add(BtResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 500, 90, 80));

        BtSum.setBackground(new java.awt.Color(49, 50, 54));
        BtSum.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtSum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtSumMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtSumMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BtSumMousePressed(evt);
            }
        });
        BtSum.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("+");
        BtSum.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 50));

        Fondo.add(BtSum, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 500, 90, 80));

        BtRes.setBackground(new java.awt.Color(49, 50, 54));
        BtRes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtRes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtResMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtResMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BtResMousePressed(evt);
            }
        });
        BtRes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("_");
        jLabel12.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BtRes.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 70, 20));

        Fondo.add(BtRes, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, 90, 80));

        Bt3.setBackground(new java.awt.Color(58, 59, 63));
        Bt3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bt3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Bt3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Bt3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Bt3MousePressed(evt);
            }
        });
        Bt3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("3");
        Bt3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 60));

        Fondo.add(Bt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, 90, 80));

        Bt0.setBackground(new java.awt.Color(58, 59, 63));
        Bt0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bt0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Bt0MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Bt0MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Bt0MousePressed(evt);
            }
        });
        Bt0.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("0");
        Bt0.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 60));

        Fondo.add(Bt0, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 500, 90, 80));

        Bt2.setBackground(new java.awt.Color(58, 59, 63));
        Bt2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bt2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Bt2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Bt2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Bt2MousePressed(evt);
            }
        });
        Bt2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("2");
        Bt2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 60));

        Fondo.add(Bt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 90, 80));

        Bt1.setBackground(new java.awt.Color(58, 59, 63));
        Bt1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Bt1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Bt1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Bt1MousePressed(evt);
            }
        });
        Bt1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("1");
        Bt1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 60));

        Fondo.add(Bt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 90, 80));

        Bt4.setBackground(new java.awt.Color(58, 59, 63));
        Bt4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bt4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Bt4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Bt4MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Bt4MousePressed(evt);
            }
        });
        Bt4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("4");
        Bt4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 60));

        Fondo.add(Bt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 90, 80));

        Bt5.setBackground(new java.awt.Color(58, 59, 63));
        Bt5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bt5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Bt5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Bt5MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Bt5MousePressed(evt);
            }
        });
        Bt5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("5");
        Bt5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 60));

        Fondo.add(Bt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 90, 80));

        Bt6.setBackground(new java.awt.Color(58, 59, 63));
        Bt6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bt6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Bt6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Bt6MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Bt6MousePressed(evt);
            }
        });
        Bt6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("6");
        Bt6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 60));

        Fondo.add(Bt6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 90, 80));

        EntryLb.setFont(new java.awt.Font("Segoe UI", 0, 64)); // NOI18N
        EntryLb.setForeground(new java.awt.Color(255, 255, 255));
        EntryLb.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        EntryLb.setText("0");
        EntryLb.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Fondo.add(EntryLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 390, 80));

        Separador.setBackground(new java.awt.Color(204, 204, 204));
        Separador.setForeground(new java.awt.Color(204, 204, 204));
        Fondo.add(Separador, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 390, 20));

        Comando.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Comando.setForeground(new java.awt.Color(153, 153, 153));
        Comando.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Fondo.add(Comando, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 390, 50));

        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClosePnMouseEntered(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
        ClosePn.setBackground(new Color(188, 32, 32));
        
    }                                       
    private void ClosePnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClosePnMouseExited
        // TODO add your handling code here:
        ClosePn.setBackground(new Color(31, 32, 36));
    }//GEN-LAST:event_ClosePnMouseExited
    private void ClosePnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClosePnMousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ClosePnMousePressed

    private void MinPnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinPnMouseEntered
        // TODO add your handling code here:
        MinPn.setBackground(new Color(58, 59, 63));
    }//GEN-LAST:event_MinPnMouseEntered
    private void MinPnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinPnMouseExited
        // TODO add your handling code here:
        MinPn.setBackground(new Color(31, 32, 36));
    }//GEN-LAST:event_MinPnMouseExited
    private void MinPnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinPnMousePressed
        // TODO add your handling code here:
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_MinPnMousePressed

    private void BarraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_BarraMousePressed
    private void BarraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse,y - yMouse);
    }//GEN-LAST:event_BarraMouseDragged
   
    private void Bt7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bt7MouseEntered
        // TODO add your handling code here:
        Bt7.setBackground(new Color(49, 50, 54));
    }//GEN-LAST:event_Bt7MouseEntered
    private void Bt7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bt7MouseExited
        // TODO add your handling code here:
        Bt7.setBackground(new Color(58, 59, 63));
    }//GEN-LAST:event_Bt7MouseExited
    private void Bt7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bt7MousePressed
        // TODO add your handling code here:
        this.agregar(7);
    }//GEN-LAST:event_Bt7MousePressed

    private void Bt8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bt8MouseEntered
        // TODO add your handling code here:
        Bt8.setBackground(new Color(49, 50, 54));
    }//GEN-LAST:event_Bt8MouseEntered
    private void Bt8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bt8MouseExited
        // TODO add your handling code here:
        Bt8.setBackground(new Color(58, 59, 63));
    }//GEN-LAST:event_Bt8MouseExited
    private void Bt8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bt8MousePressed
        // TODO add your handling code here:
        this.agregar(8);
    }//GEN-LAST:event_Bt8MousePressed

    private void Bt9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bt9MouseEntered
        // TODO add your handling code here:
        Bt9.setBackground(new Color(49, 50, 54));
    }//GEN-LAST:event_Bt9MouseEntered
    private void Bt9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bt9MouseExited
        // TODO add your handling code here:
        Bt9.setBackground(new Color(58, 59, 63));
    }//GEN-LAST:event_Bt9MouseExited
    private void Bt9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bt9MousePressed
        // TODO add your handling code here:
        this.agregar(9);
    }//GEN-LAST:event_Bt9MousePressed

    private void BtDivMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtDivMouseEntered
        // TODO add your handling code here:
        BtDiv.setBackground(new Color(58, 59, 63));
        
    }//GEN-LAST:event_BtDivMouseEntered
    private void BtDivMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtDivMouseExited
        // TODO add your handling code here:
        BtDiv.setBackground(new Color(49, 50, 54));
    }//GEN-LAST:event_BtDivMouseExited
    private void BtDivMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtDivMousePressed
        // TODO add your handling code here:
        op = 4;
        temp = Integer.parseInt(EntryLb.getText());
        Comando.setText(EntryLb.getText() + " / ");
        EntryLb.setText("0");
    }//GEN-LAST:event_BtDivMousePressed

    private void BtMultMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtMultMouseEntered
        // TODO add your handling code here:
        BtMult.setBackground(new Color(58, 59, 63));
    }//GEN-LAST:event_BtMultMouseEntered

    private void BtMultMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtMultMouseExited
        // TODO add your handling code here:
        BtMult.setBackground(new Color(49, 50, 54));
    }//GEN-LAST:event_BtMultMouseExited

    private void BtMultMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtMultMousePressed
        // TODO add your handling code here:
        op = 3;
        temp = Integer.parseInt(EntryLb.getText());
        Comando.setText(EntryLb.getText() + " x ");
        EntryLb.setText("0");
    }//GEN-LAST:event_BtMultMousePressed

    private void Bt4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bt4MouseEntered
        // TODO add your handling code here:
        Bt4.setBackground(new Color(49, 50, 54));
    }//GEN-LAST:event_Bt4MouseEntered
    private void Bt4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bt4MouseExited
        // TODO add your handling code here:
        Bt4.setBackground(new Color(58, 59, 63));
    }//GEN-LAST:event_Bt4MouseExited
    private void Bt4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bt4MousePressed
        // TODO add your handling code here:
        this.agregar(4);
    }//GEN-LAST:event_Bt4MousePressed
    
    private void Bt5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bt5MouseEntered
        // TODO add your handling code here:
        Bt5.setBackground(new Color(49, 50, 54));
    }//GEN-LAST:event_Bt5MouseEntered
    private void Bt5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bt5MouseExited
        // TODO add your handling code here:
        Bt5.setBackground(new Color(58, 59, 63));
    }//GEN-LAST:event_Bt5MouseExited
    private void Bt5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bt5MousePressed
        // TODO add your handling code here:
        this.agregar(5);
    }//GEN-LAST:event_Bt5MousePressed

    private void Bt6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bt6MouseEntered
        // TODO add your handling code here:
        Bt6.setBackground(new Color(49, 50, 54));
    }//GEN-LAST:event_Bt6MouseEntered
    private void Bt6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bt6MouseExited
        // TODO add your handling code here:
        Bt6.setBackground(new Color(58, 59, 63));
    }//GEN-LAST:event_Bt6MouseExited
    private void Bt6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bt6MousePressed
        // TODO add your handling code here:
        this.agregar(6);
    }//GEN-LAST:event_Bt6MousePressed

    private void Bt1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bt1MouseEntered
        // TODO add your handling code here:
        Bt1.setBackground(new Color(49, 50, 54));
    }//GEN-LAST:event_Bt1MouseEntered
    private void Bt1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bt1MouseExited
        // TODO add your handling code here:
        Bt1.setBackground(new Color(58, 59, 63));
    }//GEN-LAST:event_Bt1MouseExited
    private void Bt1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bt1MousePressed
        // TODO add your handling code here:
        this.agregar(1);
    }//GEN-LAST:event_Bt1MousePressed

    private void Bt2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bt2MouseEntered
        // TODO add your handling code here:
        Bt2.setBackground(new Color(49, 50, 54));
    }//GEN-LAST:event_Bt2MouseEntered
    private void Bt2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bt2MouseExited
        // TODO add your handling code here:
        Bt2.setBackground(new Color(58, 59, 63));
    }//GEN-LAST:event_Bt2MouseExited
    private void Bt2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bt2MousePressed
        // TODO add your handling code here:
        this.agregar(2);
    }//GEN-LAST:event_Bt2MousePressed

    private void Bt3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bt3MouseEntered
        // TODO add your handling code here:
        Bt3.setBackground(new Color(49, 50, 54));
    }//GEN-LAST:event_Bt3MouseEntered
    private void Bt3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bt3MouseExited
        // TODO add your handling code here:
        Bt3.setBackground(new Color(58, 59, 63));
    }//GEN-LAST:event_Bt3MouseExited
    private void Bt3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bt3MousePressed
        // TODO add your handling code here:
        this.agregar(3);
    }//GEN-LAST:event_Bt3MousePressed

    private void BtResMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtResMouseEntered
        // TODO add your handling code here:
        BtRes.setBackground(new Color(58, 59, 63));
    }//GEN-LAST:event_BtResMouseEntered
    private void BtResMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtResMouseExited
        // TODO add your handling code here:
        BtRes.setBackground(new Color(49, 50, 54));
    }//GEN-LAST:event_BtResMouseExited
    private void BtResMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtResMousePressed
        // TODO add your handling code here:
        op = 2;
        temp = Integer.parseInt(EntryLb.getText());
        Comando.setText(EntryLb.getText() + " + ");
        EntryLb.setText("0");
    }//GEN-LAST:event_BtResMousePressed

    private void BtSumMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtSumMouseEntered
        // TODO add your handling code here:
        BtSum.setBackground(new Color(58, 59, 63));
    }//GEN-LAST:event_BtSumMouseEntered
    private void BtSumMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtSumMouseExited
        // TODO add your handling code here:
        BtSum.setBackground(new Color(49, 50, 54));
    }//GEN-LAST:event_BtSumMouseExited
    private void BtSumMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtSumMousePressed
        // TODO add your handling code here:
        op = 1;
        temp = Integer.parseInt(EntryLb.getText());
        Comando.setText("");
        Comando.setText(EntryLb.getText() + " + ");
        EntryLb.setText("0");
    }//GEN-LAST:event_BtSumMousePressed

    private void Bt0MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bt0MouseEntered
        // TODO add your handling code here:
        Bt0.setBackground(new Color(49, 50, 54));
    }//GEN-LAST:event_Bt0MouseEntered
    private void Bt0MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bt0MouseExited
        // TODO add your handling code here:
        Bt0.setBackground(new Color(58, 59, 63));
    }//GEN-LAST:event_Bt0MouseExited
    private void Bt0MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bt0MousePressed
        // TODO add your handling code here:
        this.agregar(0);
    }//GEN-LAST:event_Bt0MousePressed

    private void BtResultMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtResultMouseEntered
        // TODO add your handling code here:
        BtResult.setBackground(new Color(58, 59, 63));
    }//GEN-LAST:event_BtResultMouseEntered
    private void BtResultMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtResultMouseExited
        // TODO add your handling code here:
        BtResult.setBackground(new Color(49, 50, 54));
    }//GEN-LAST:event_BtResultMouseExited
    private void BtResultMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtResultMousePressed
        // TODO add your handling code here:
        long resultado = 0;
        if (op != 0 && (op != 4 || !EntryLb.getText().equals("0"))){
            String []operaciones = {" + ", " - ", " x ", " / "};
            Comando.setText(String.valueOf(temp) + operaciones[op-1] + EntryLb.getText() + " =");
            if (op == 1){
                resultado = temp + Integer.parseInt(EntryLb.getText());
            }else if (op == 2){
                resultado = temp - Integer.parseInt(EntryLb.getText());
            }else if (op == 3){
                resultado = temp * Integer.parseInt(EntryLb.getText());
            }else if (op == 4){
                resultado = temp / Integer.parseInt(EntryLb.getText());
            }
        }
        EntryLb.setText(String.valueOf(resultado));
    }//GEN-LAST:event_BtResultMousePressed

    private void BtClearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtClearMouseEntered
        // TODO add your handling code here:
        BtClear.setBackground(new Color(58, 59, 63));
    }//GEN-LAST:event_BtClearMouseEntered
    private void BtClearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtClearMouseExited
        // TODO add your handling code here:
        BtClear.setBackground(new Color(49, 50, 54));
    }//GEN-LAST:event_BtClearMouseExited
    private void BtClearMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtClearMousePressed
        // TODO add your handling code here:
        res = 0;
        EntryLb.setText(String.valueOf(res));
        Comando.setText("");
    }//GEN-LAST:event_BtClearMousePressed

    private void agregar(int n) {
        int number = Integer.parseInt(EntryLb.getText());
        number = number*10 + n;
        res = number;
        EntryLb.setText(String.valueOf(number));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Barra;
    private javax.swing.JPanel Bt0;
    private javax.swing.JPanel Bt1;
    private javax.swing.JPanel Bt2;
    private javax.swing.JPanel Bt3;
    private javax.swing.JPanel Bt4;
    private javax.swing.JPanel Bt5;
    private javax.swing.JPanel Bt6;
    private javax.swing.JPanel Bt7;
    private javax.swing.JPanel Bt8;
    private javax.swing.JPanel Bt9;
    private javax.swing.JPanel BtClear;
    private javax.swing.JPanel BtDiv;
    private javax.swing.JPanel BtMult;
    private javax.swing.JPanel BtRes;
    private javax.swing.JPanel BtResult;
    private javax.swing.JPanel BtSum;
    private javax.swing.JLabel CloseLb;
    private javax.swing.JPanel ClosePn;
    private javax.swing.JLabel Comando;
    private javax.swing.JLabel EntryLb;
    private javax.swing.JPanel Fondo;
    private javax.swing.JLabel Icono;
    private javax.swing.JLabel MinLb;
    private javax.swing.JPanel MinPn;
    private javax.swing.JSeparator Separador;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
